
# cargo-vet audits file

[audits]

[[trusted.blob-decoder]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.ewf]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-03-05"
end = "2027-08-07"

[[trusted.forensic-carve]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-23"
end = "2027-08-01"

[[trusted.forensic-vfs]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-07"
end = "2027-08-07"

[[trusted.forensicnomicon]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-05"
end = "2027-08-07"

[[trusted.forensicnomicon-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-07"

[[trusted.forensicnomicon-data]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-07"

[[trusted.jsonguard]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-05-21"
end = "2027-08-07"

[[trusted.protobuf-forensic-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-11"
end = "2027-08-01"

[[trusted.safe-decode]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-08-02"
end = "2027-08-07"

[[trusted.safe-read]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-15"
end = "2027-08-07"

[[trusted.state-history-forensic]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-16"
end = "2027-08-07"
